// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/visualizer/:id": {
    params: {
      "id": string;
    };
  };
  "/api/projects": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/blueprint/new": {
    params: {};
  };
  "/features": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/visualizer/:id" | "/api/projects" | "/community" | "/blueprint/new" | "/features";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/visualizer.$id.tsx": {
    id: "routes/visualizer.$id";
    page: "/visualizer/:id";
  };
  "./routes/api.projects.tsx": {
    id: "routes/api.projects";
    page: "/api/projects";
  };
  "./routes/community.tsx": {
    id: "routes/community";
    page: "/community";
  };
  "./routes/blueprint.new.tsx": {
    id: "routes/blueprint.new";
    page: "/blueprint/new";
  };
  "./routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/visualizer.$id": typeof import("./app/./routes/visualizer.$id.tsx");
  "routes/api.projects": typeof import("./app/./routes/api.projects.tsx");
  "routes/community": typeof import("./app/./routes/community.tsx");
  "routes/blueprint.new": typeof import("./app/./routes/blueprint.new.tsx");
  "routes/features": typeof import("./app/./routes/features.tsx");
};